pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Fabric Snapshots'
            url = 'https://maven.fabricmc.net/repository/snapshots/'
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

repositories {
    maven {
        name = 'Mojang'
        url = 'https://libraries.minecraft.net/'
    }
}

rootProject.name = 'hardcoreworldmod'
