pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Fabric Snapshots'
            url = 'https://maven.fabricmc.net/repository/snapshots/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'hardcoreworldmod'
